config/routes.rb
Rails.application.routes.draw do
  # ’topics/show/:id’へのアクセスは => topicsコントローラのshowメソッドが受け取る。
  # topics_showという識別子を付与することで、プログラムからルーティングを特定できる
  get 'topics/show/:id' => 'topics#show', as: :topics_show
  # topicを新規登録する際に使用するルーティング
  # 新規でデータを登録したいのでpostを使用する
  post 'topics/create' => 'topics#create'
  delete 'topics/delete/:id' => 'topics#delete', as: :topic_delete
  post 'posts/create' => 'post#create', as: :post_create


  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # ログイン後の画面設定
  root to: 'topics#index'


  # get 'URLの設定', to: '〇〇コントローラーの＃〇〇アクションを呼び出す'
  get 'tweets', to: 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  # このモデルを生成したコマンド
  # rails g model Post name body:text topic:references
  # topic:references = Postモデルのカラムをtopicテーブルに紐づけている
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # 共通の処理を書くことのできるファイル

    # リクエストしてきたユーザーを認証する。
    # ユーザーがログイン済みの場合はアクセスを許可して、未ログインの場合はroot_pathにリダイレクトする。
    before_action :authenticate_user!

    def index
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController

    def create
        @post = Post.new(params[:post].permit(:topic_id, :name, :body))
        @post.save
        redirect_to topics_show_path(params[:post]['topic_id'])
    end

    def delete
        @posts = Post.find(params[:id])
        @posts.destroy
    end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # topics/indexへのアクセスをここで受け取るので、DBのトピック一覧を取得し、ビューに渡す
  def index
    # テーブル名 = モデル名.all
    # 先頭の文字を大文字にするとモデルにアクセスできる
    # topicsテーブルの全ての中身を.allで取得
    @topics = Topic.all
    # モデルオブジェクトの生成
    @newTopic = Topic.new
  end

  # フォームから送られてきたデータを保存するためのアクション
  def create
    # モデルオブジェクトの生成
    # params[:topic] = topic新規登録フォームで送られてきた値を受け取る引数
    # permit(:title) = paramsのタイトルを保存できるように許可を出すメソッド
    @topic = Topic.new(params[:topic].permit(:title))
    # フォームから送られてきたデータを保存
    @topic.save
    # ボタンを押した際にルートバスにリダイレクト
    redirect_to root_path
  end

  # トピック一覧の該当箇所の削除ボタンを押したときのアクション
  def delete
    # Topic.find(params[:id]) = モデルと紐づいているデータベースのテーブルから、レコードを一つ取り出している
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to root_path
  end

  def show
    @topic = Topic.find(params[:id])
    # where = テーブル内の条件に一致したレコードを配列で取得できる
    @posts = Post.where(topic_id: params[:id])
    # 書き込み一覧でform_forメソッドを使うため、Postモデルの生成
    @newpost = Post.new(:topic_id => params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/home/index.html.erb
<%# ログアウトボタン %>
<%= link_to 'ログアウト', 
    destroy_user_session_path,
    class: 'dropdown-item',
    method: :delete,
    class: "logout"
%>


<div class="main">
    <div class="home__index">
        <p class="home__index-text">
            rootのページです
        </p>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'destyle', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'home', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/layouts/flash/_flash.html.erb
# flashメッセージ。noticeとalertという変数に格納されている

<% if notice %>
    <p><%= notice %></p>
<% end %>
<% if alert %>
    <p><%= alert %></p>
<% end %>

app/views/topics/index.html.erb
<%# ログアウトボタン %>
<%= link_to 'ログアウト', 
    destroy_user_session_path,
    class: 'dropdown-item',
    method: :delete,
    class: "logout"
%>


<div class="topic">
    <div class="topic__inner">

        <div class="topic__form-wrap">
            <h1 class="topic__form-ttl">トピック新規登録</h1>
            <%# 登録先を@newTopicで指定 %>
            <%# :url => {:action}でcreateアクションを指定 %>
            <%= form_for @newTopic, :url => {:action => 'create'} do |f| %>
                <%= f.text_field :title, class: 'topic__form-input' %>
                <%= f.submit %>
            <% end %>
        </div>

        <div class="topic__box">
            <h1 class="topic__box-ttl">トピック一覧</h1>
            <ul class="topic__list">
                <%# コントローラーのtopicsで取得した、DBのtopicsを取得 %>
                <% @topics.each do |topic| %>
                    <li class="topic__list-item">
                        <%# DBのtopicsのカラムの表示 %>
                        <%# link_to = aタグの生成 %>
                        <%# topic.title = のタイトルの表示 %>
                        <%# topics_show_path()でidの取得 %>
                        <%= link_to topic.title, topics_show_path(topic.id) %>
                        <%# DBのtopicsのカラムの削除 %>
                        <%# method: :delete = topicsコントローラーのdeleteアクションを指定 %>
                        <%# data: {confirm: ''} = ボタンを押下した際に画面上にアラートが出る %>
                        <%= link_to '[削除]', topic_delete_path(topic.id), method: :delete, data: {confirm: "削除してもよろしいですか？"} %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/topics/show.html.erb
<div class="show">
    <div class="show__inner">

        <div class="show__form-wrap">
            <h3 class="show__form-ttl">新規書き込み</h3>
            <%= form_for @newpost, :url => post_create_path do |f| %>
                <p class="show__form-label">お名前</p>
                <p><%= f.text_field :name, class: 'show__form-input' %></p>
                <p class="show__form-label">本文</p>
                <p><%= f.text_area :body, class: 'show__form-input' %></p>
                <%= f.hidden_field :topic_id %>
                <%= f.submit class: 'show__form-submit' %>
            <% end %>
        </div>

        <div class="show__box">
            <%# topicsコントローラーのshowメソッドで取得したTopicモデルの該当IDのレコードのタイトルを表示させている %>
            <h1 class="show__box-ttl"><%= @topic.title %></h1>
            <%# Postのレコードをループしつつ、それぞれにインデックス番号を割り当てる %>
            <%# @posts = post %>
            <%# インデックス番号 = idx %>
            <% @posts.each_with_index do |post , idx| %>
                <p>
                    <%# idxで投稿の番号を表示 %>
                    <%= idx + 1 %>. <%= post.name %> : <%= post.body %>
                    <%# <%= link_to '[削除]', post_delete_path(post.id), method: :delete, data: {confirm: "削除してもよろしいですか？"} %>
                </p>
            <% end %>

        </div>
    </div>
</div>

app/views/tweets/index.html.erb
<h1>ハローワールド</h1>